### ISSUE TITLE
Lack of file “BFM09_model_info.mat”

### ISSUE THREAD

**Issue by 675492062** [wuhaozhe/pytorch-nicp#2]
Traceback (most recent call last):
  File "demo_nicp.py", line 28, in <module>
    bfm_meshes, bfm_lm_index = load_bfm_model(torch.device('cuda:0'))
  File "/data/pytorch-nicp/bfm_model.py", line 15, in load_bfm_model
    bfm_meta_data = loadmat('BFM/BFM09_model_info.mat')
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 224, in loadmat
    with _open_file_context(file_name, appendmat) as f:
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 17, in _open_file_context
    f, opened = _open_file(file_like, appendmat, mode)
  File "/root/anaconda3/envs/pytorch3d/lib/python3.8/site-packages/scipy/io/matlab/mio.py", line 45, in _open_file
    return open(file_like, mode), True
FileNotFoundError: [Errno 2] No such file or directory: 'BFM/BFM09_model_info.mat'

 In 3DMMfitting-pytorch， there are only these files:
BFM_exp_idx.mat
BFM_front_idx.mat
facemodel_info.mat
README.md
select_vertex_id.mat
similarity_Lm3D_all.mat
std_exp.txt

**Comment by wuhaozhe** [comment]
Hey, just run the demo of 3DMMfitting-pytorch, then you can obtain BFM09_model_info.mat

**Comment by 675492062** [comment]
wow, thanks a lot for your kindly reply.
