### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by 675492062** [wuhaozhe/pytorch-nicp#3]
Traceback (most recent call last):
  File "demo_nicp.py", line 27, in <module>
    target_lm_index, lm_mask = get_mesh_landmark(norm_meshes, dummy_render)
  File "/data/pytorch-nicp/landmark.py", line 37, in get_mesh_landmark
    row_index = row_index.unsqueeze(2).unsqueeze(3).expand(landmarks.shape[0], landmarks.shape[1], shape_img.shape[2], shape_img.shape[3])
RuntimeError: The expanded size of the tensor (1) must match the existing size (2) at non-singleton dimension 1.  Target sizes: [1, 1, 512, 3].  Tensor sizes: [1, 2, 1, 1]

I have already configure the environment，but it seems have some problems in the code.What can I do to solve this problem.

**Comment by wuhaozhe** [comment]
hey, can you print the following information 
```
def get_mesh_landmark(meshes: Meshes, dummy_renderer: MeshRenderer):
    '''
        The meshes should be textured
    '''
    global fa

    device = meshes.device
    mesh_verts = meshes.verts_padded()
    mesh_faces = meshes.faces_padded()
    textures = TexturesVertex(mesh_verts)
    shape_meshes = Meshes(mesh_verts, mesh_faces, textures)
    rgb_img = dummy_renderer(meshes)[:, :, :, 0, :]
    shape_img = dummy_renderer(shape_meshes)[:, :, :, 0, :]
    rgb_img_uint8 = (rgb_img * 255).permute(0, 3, 1, 2)
    landmarks = fa.get_landmarks_from_batch(rgb_img_uint8)
    landmarks = torch.from_numpy(np.array(landmarks)).to(device).long()

    row_index = landmarks[:, :, 1].view(landmarks.shape[0], -1)
    column_index = landmarks[:, :, 0].view(landmarks.shape[0], -1)
    print(row_index.shape, landmarks.shape, shape_img.shape)
    row_index = row_index.unsqueeze(2).unsqueeze(3).expand(landmarks.shape[0], landmarks.shape[1], shape_img.shape[2], shape_img.shape[3])
```

My output is torch.Size([1, 68]) torch.Size([1, 68, 2]) torch.Size([1, 512, 512, 3])

**Comment by zouyoucheng27** [comment]
The output is torch.Size([1, 2]) torch.Size([1, 1, 68, 2]) torch.Size([1, 512, 512, 3]) which is different from yours.I suspect there is something wrong with my model.Could you please give a link that contant your model(BFM09_model_info.mat)?

**Comment by wuhaozhe** [comment]
Hi, here is my link, https://cloud.tsinghua.edu.cn/f/1590206609fc4d058ef0/?dl=1

**Comment by zouyoucheng27** [comment]
Hi!Thanks for your kind reply.But it still has some problems with torch.Size.I can't get the same size with yours.

**Comment by wuhaozhe** [comment]
Hi, with landmarks: `landmarks = torch.from_numpy(np.array(landmarks)).to(device).long()`, maybe you can  reshape landmarks from torch.Size([1, 1, 68, 2]) to  torch.Size([1, 68, 2])

**Comment by zouyoucheng27** [comment]
Hi,I turn on the (save texture = True),then I get error as AttributeError: 'TexturesVertex' object has no attribute 'maps_padded'.
How can I solve it?Can the code process texture?

**Comment by wuhaozhe** [comment]
hi, currently we cannot save textures, because the uv coordinates of registered mesh is unknown

**Comment by zouyoucheng27** [comment]
Thanks for your kind reply.I look forward to your rich features.
